### ISSUE TITLE
WordPress Filesystem API and directory permissions

### ISSUE THREAD

**Issue by widoz** [inpsyde/assets#2]
I was wondering to understand if there's a particular reason to not use the WordPress Filesystem Api to create and write file/directories and in regards of the permissions why not using the WordPress built in permissions `FS_CHMOD_DIR` and `FS_CHMOD_FILE`?  

https://github.com/inpsyde/assets/blob/a788809f50ad2c1ad8e966b64154ca5c475f1722/inc/functions.php#L69

**Comment by Chrico** [comment]
The problem with `WP_Filesytem()` is, that everyone can replace that, which might causes problems if some methods are not supported or default permissions are changed within the custom implementation. We want to ensure, that this always works (creating symlinks/folders into that folder). 

But yes, we can might be change a bit the permissions to not "too open". 👍

**Comment by gmazzap** [comment]
- Hardcoded 0777 is quite bad. We allow anyone to write there
- We should use [`wp_mkdir_p`](https://developer.wordpress.org/reference/functions/wp_mkdir_p/) that is the same that use WordPress and _calculates_ the permission based on the parent folder

So that

` if (!is_dir($rootPath) && ! mkdir($rootPath, 0777)) { `

becomes

` if (!is_dir($rootPath) && !wp_mkdir_p($rootPath)) {`

**Comment by Chrico** [comment]
Implemented the change here: https://github.com/inpsyde/assets/commit/a00cfc5849298f8216ab374560ec5044a3acf51e - will be part of the next release. 👍
