### ISSUE TITLE
It's not possible to disable dependencies from the Dependency Extraction Plugin

### ISSUE THREAD

**Issue by shvlv** [inpsyde/assets#39]
**Describe the bug**
While `Script::useDependencyExtractionPlugin` method returns `false` `Script::resolveDependencyExtractionPlugin` method is invokated behind the scene for any version or dependencies retrieving.

**To Reproduce**
1. Setup webpack configuration with `DependencyExtractionWebpackPlugin`.
2. Build assets.
3. Load assets via `PhpFileLoader`. 
4. Set debug breakpoint to the https://github.com/inpsyde/assets/blob/master/src/Handler/ScriptHandler.php#L70 point.
5. Ensure your script has all dependencies from `*.asset.php` file.

**Expected behavior**
Control registering dependencies.

**Additional context**
Suggestions:
1. Add counterpart `Script::disableDependencyExtractionPlugin` method.
2. Check `Script::$useDependencyExtractionPlugin` variable within `Script::resolveDependencyExtractionPlugin` method.

**Comment by Chrico** [comment]
> While `Script::useDependencyExtractionPlugin` method returns false

Why does this method return `false`? It's returning `$this` https://github.com/inpsyde/assets/blob/master/src/Script.php#L218 🤔 

I think here we have 2 different topics:

a) The `PhpFileLoader` does not support `Script::useDependencyExtractionPlugin()` like the [`AbstractWebpackLoader`](https://github.com/inpsyde/assets/blob/master/src/Loader/AbstractWebpackLoader.php#L139-L142) - which is okay, beause we don't know the build tool if we use `PhpFileLoader`

b) Adding a counterpart to disable the dependency extraction Plugin - which is not required because the [`Script::$useDependencyExtractionPlugin = false`](https://github.com/inpsyde/assets/blob/master/src/Script.php#L50)....why would you enable it to disable it afterwards? 🙈 

I guess for a) it's maybe easier instead of using the `PhpFileLoader` to instance your `Script` and enable it actively if you don't want to use a Webpack-based Loader:

```php
$script = (new Script('handle', 'handle.js'))
   ->useDependencyExtractionPlugin();
```

**Comment by shvlv** [comment]
@Chrico Sorry, maybe my question was unclear. I don't need `DependencyExtractionPlugin` but it's not possible to *disable* it. Dependencies are loaded regardless `Script::$useDependencyExtractionPlugin` value.

**Comment by Chrico** [comment]
I see. So it seems that here https://github.com/inpsyde/assets/blob/master/src/Script.php#L254 a check is missing for `$this->useDependencyExtractionPlugin` to be `false` end then return. 🤔 Do you have time to create a Pull Request + add some Tests for this? :)

**Comment by shvlv** [comment]
I agree there is an edge case. Usually, we have the single Webpack config for several entires. And it's possible when we want auto discovering dependencies for some assets and manually defined for others. So flexibility is an important point I think.

Another option could be to allow rewrite dependencies: https://github.com/inpsyde/assets/blob/6d70c645a539671dce2ee4d0e8d78bfa0f9447a7/src/BaseAsset.php#L220-L228.

What do you think about the following method?
```php
    public function replaceDependencies(string ...$dependencies): Asset
    {
        $this->dependencies = $dependencies;

        return $this;
    }

```
