### ISSUE TITLE
Ajax context

### ISSUE THREAD

**Issue by nlemoine** [inpsyde/assets#41]
**Is your feature request related to a problem? Please describe.**

I don't really know if this is a feature or a bug.

I'm doing some dynamic rendering in the backend using WordPress AJAX (admin-ajax.php). Problem: my frontend stylesheet isn't enqueued because it's considered a front end request by the hook resolver.

Actually, the `isAjax` context isn't handled at all. I'm aware `admin-ajax.php` isn't the best option to deal with this but I have no choice here (plugin). 

Is the `isAjax` something you would agree to handle?

**Describe the solution you'd like**

Since ajax can used almost anywhere, this context should probably resolve almost every hook.

**Describe alternatives you've considered**

Extending the hook resolver class but the private $context makes it hard to extend: 
- https://github.com/inpsyde/assets/pull/40

**Comment by Chrico** [comment]
Hey ☕ 

The `inspyde/assets` uses [`inpsyde/wp-context`](https://github.com/inpsyde/wp-context/) to [resolve locations](https://github.com/inpsyde/assets/blob/master/src/Util/AssetHookResolver.php#L39). 

The problem with admin-ajax.php is, that it does not use [any hook](https://github.com/inpsyde/assets/blob/master/src/Asset.php#L29-L36) to enqueue assets, so we cannot bind `isAjax` to something, because in theory every of those hooks - and none - can be manually called. 🤔 

I guess we need to find a smart way to allow extending the `AssetManager` - which already allows to set `AssetHookResolver` in constructor. Might be worth to finally start moving to `inpsyde/modularity` for this package to have an easier extendable API. :)

**Comment by nlemoine** [comment]
Thanks for your valuable feedback! Can you still have a look at my PR (https://github.com/inpsyde/assets/pull/40) ? All AJAX stuff apart, I think it's still relevant and legitimate.

**Comment by Chrico** [comment]
#40 was merged and is part of the 2.8.1 release. I guess we can close that issue?! ;)

**Comment by nlemoine** [comment]
Yep! Thanks :)
